version: '3'

services:
  nginx:
    #    build: ./nginx
    image: nginx-test
    container_name: "nginx"
    restart: always
    ports:
      - "8880:80"
      - "443:443"
    depends_on:
      - "php"
    volumes:
      - "/d/website/docker/nginx/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf"
      - "/d/code:/home/wwwroot"
    networks:
      - net-web

  php:
    #    build: ./php
    image: php7.4:latest
    container_name: "php"
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "/d/code:/home/wwwroot"
    networks:
      - net-web

networks:
  net-web:
